name: Build and publish

on:
  schedule:
  - cron: "40 23 * * *"
  workflow_dispatch:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build_pages:
    name: Publish Transcription Status
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - name: fetch the data
        run: python fetch_data.py
      - name: make geojson
        run: python make_geojson.py
      - name: make charts json
        run: python make_chartsjson.py
      - name: build
        run: python build.py
      - name: Commit data
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Data update
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          publish_dir: ./html
